---
# tasks file for test1
- name: test1 modules
  hosts: all
  tasks:
    - name: package module 
      apt:
        name: " {{ java_package }}"
        state: present
      become: true

    - name: file module
      file:
        src: path of the file
        dest: "{{ destination_folder }}"
      
