---
# tasks file for jenkins
- name: First add the repository key to the system
  apt_key:
     url: "{{ jenkins_url }}" 
     state: present

- name: ensure the repository is configured
  apt_repository:
    repo: "{{ jenkins_deb_repo }}"
    state: present

- name: apt update
  apt:
    name: jenkins
    update_cache: true
  become: true

- name: insatll jenkins
  service:
    name: "{{ jenkins_package }}"
    state: started
  become: true
